#:schema node_modules/wrangler/config-schema.json
name = "worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "f0cbdb9a3849452ba2ed2366ae01668b" }
]

[assets]
directory = "./public"
